name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go on ${{ matrix.os }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build on ${{ matrix.os }}
      run: go build -v ./...

    - name: Test on ${{ matrix.os }}
      run: go test -v ./...
